parameters:
#    param: value

#liip_imagine:
#    filter_sets:
#        demo_site_thumb:
#            format: jpeg
#            quality: 100
#            filters:
#                thumbnail: { size: [207, 177], mode: inset }
