unicat_admin:
    path: /
    defaults:
        _controller: UnicatModule:AdminUnicat:index

unicat_admin.configuration:
    path: /{configuration}/
    defaults:
        _controller: UnicatModule:AdminUnicat:configuration

unicat_admin.configuration.settings:
    path: /{configuration}/settings/
    defaults:
        _controller: UnicatModule:AdminUnicat:configurationSettings

# Structure
unicat_admin.structures_index:
    path: /{configuration}/structure/
    defaults:
        _controller: UnicatModule:AdminStructure:index

unicat_admin.structure_create:
    path: /{configuration}/structure/create/
    defaults:
        _controller: UnicatModule:AdminStructure:create

unicat_admin.structure:
    path: /{configuration}/structure/{id}/
    defaults:
        _controller: UnicatModule:AdminStructure:structure
    requirements:
        id: \d+

unicat_admin.structure_with_parent_id:
    path: /{configuration}/structure/{id}/{parent_id}/
    defaults:
        _controller: UnicatModule:AdminStructure:structure
    requirements:
        parent_id: \d+
        id: \d+

unicat_admin.structure_edit:
    path: /{configuration}/structure/{id}/edit/
    defaults:
        _controller: UnicatModule:AdminStructure:edit
    requirements:
        id: \d+

unicat_admin.category:
    path: /{configuration}/structure/{structure_id}/category_{id}/
    defaults:
        _controller: UnicatModule:AdminStructure:categoryEdit
    requirements:
        id: \d+
        structure_id: \d+

# Attributes
unicat_admin.attributes_index:
    path: /{configuration}/attributes/
    defaults:
        _controller: UnicatModule:AdminAttributes:index

unicat_admin.attributes_group_create:
    path: /{configuration}/attributes/create_group/
    defaults:
        _controller: UnicatModule:AdminAttributes:createGroup

unicat_admin.attributes:
    path: /{configuration}/attributes/group_{group_id}/
    defaults:
        _controller: UnicatModule:AdminAttributes:group
    requirements:
        group_id: \d+

unicat_admin.attribute:
    path: /{configuration}/attributes/group_{group_id}/{id}/
    defaults:
        _controller: UnicatModule:AdminAttributes:edit
    requirements:
        group_id: \d+
        id: \d+

# Items
unicat_admin.item_create:
    path: /{configuration}/item_create/
    defaults:
        _controller: UnicatModule:AdminUnicat:itemCreate

unicat_admin.item_create_in_category:
    path: /{configuration}/item_create/{default_category_id}/
    requirements:
        default_category_id: \d+
    defaults:
        _controller: UnicatModule:AdminUnicat:itemCreate

unicat_admin.item_edit:
    path: /{configuration}/item_{id}/
    defaults:
        _controller: UnicatModule:AdminUnicat:itemEdit
    requirements:
        id: \d+
