
smart_module.menu.admin:
    path: /
    defaults:
        _controller: MenuModule:Admin:index

smart_module.menu.admin_menu:
    path: /{menu_id}
    defaults:
        _controller: MenuModule:Admin:menu
    requirements:
        menu_id: \d+

smart_module.menu.admin_menu_edit:
    path: /{menu_id}/edit
    defaults:
        _controller: MenuModule:Admin:menuEdit
    requirements:
        menu_id: \d+

smart_module.menu.admin_item:
    path: /item/{item_id}
    defaults:
        _controller: MenuModule:Admin:item
    requirements:
        item_id: \d+
