
smart_menu_admin:
    path: /
    defaults:
        _controller: MenuModule:Admin:index

smart_menu_admin_group:
    path: /{group_id}
    defaults:
        _controller: MenuModule:Admin:group
    requirements:
        group_id: \d+

smart_menu_admin_group_edit:
    path: /{group_id}/edit
    defaults:
        _controller: MenuModule:Admin:groupEdit
    requirements:
        group_id: \d+

smart_menu_admin_item:
    path: /item/{item_id}
    defaults:
        _controller: MenuModule:Admin:item
    requirements:
        item_id: \d+
