smart_sitemap:
    base_url:  http://example.org
    limit:     50000
    target:    %kernel.root_dir%/../web
    ignores:
        - /blog/tag/
        - /blog/archive/
        - /blog/category/
        - *sort=            # @todo
