
smart_module.texter.api:
    path: /
    methods: 'GET'
    defaults:
        _controller: TexterModule:ApiTexter:json

smart_module.texter.api_html:
    path: /html
    methods: 'GET'
    defaults:
        _controller: TexterModule:ApiTexter:html

smart_module.texter.api_html_w_slash:
    path: /html/
    methods: 'GET'
    defaults:
        _controller: TexterModule:ApiTexter:html
