
smart_module.texter.admin:
    path: /
    defaults:
        _controller: TexterModule:Admin:index

smart_module.texter.admin.history:
    path: /{id}/history
    defaults:
        _controller: TexterModule:Admin:history
    requirements:
        id: \d+

smart_module.texter.admin.rollback:
    path: /rollback/{id}/
    defaults:
        _controller: TexterModule:Admin:rollback
    requirements:
        id: \d+

smart_module.texter.admin.edit:
    path: /{id}/
    defaults:
        _controller: TexterModule:Admin:item
    requirements:
        id: \d+
