
smart_module.gallery.admin:
    path: /
    defaults:
        _controller: GalleryModule:AdminGallery:index

smart_module.gallery.admin_gallery:
    path: /gallery_{id}/
    defaults:
        _controller: GalleryModule:AdminGallery:gallery

smart_module.gallery.admin_gallery_edit:
    path: /gallery_{id}/edit/
    defaults:
        _controller: GalleryModule:AdminGallery:galleryEdit

smart_module.gallery.admin_album:
    path: /gallery_{gallery_id}/album_{id}/
    defaults:
        _controller: GalleryModule:AdminGallery:album

smart_module.gallery.admin_album_edit:
    path: /gallery_{gallery_id}/album_{id}/edit/
    defaults:
        _controller: GalleryModule:AdminGallery:albumEdit

smart_module.gallery.admin_photo_make_cover:
    path: /gallery_{gallery_id}/album_{album_id}/photo_{id}/make_cover/
    defaults:
        _controller: GalleryModule:AdminGallery:photo
        set_as_cover: true

smart_module.gallery.admin_photo:
    path: /gallery_{gallery_id}/album_{album_id}/photo_{id}/
    defaults:
        _controller: GalleryModule:AdminGallery:photo
